name = "TDR OBJ"
grammar = "tdr_obj"
path_suffixes = ["obj"]
line_comments = ["#"]
tab_size = 2
hard_tabs = false
brackets = [
  { start = "(", end = ")", close = true, newline = false }
]
folds = "tree"
